### ISSUE TITLE
ApphudListener doesn't calls if firebase_messaging plugin initialized

### ISSUE THREAD

**Issue by NiKoTron** [apphud/ApphudSDK-Flutter#38]
There is a [known issue](https://github.com/flutter/flutter/issues/69721) if we use the firebase messaging plugin onAttachedToEngine will call twice.
Due to this there two instances of ApphudListenerHandler are created as a result, the flutter plugin won't receive any callbacks that come through ApphudListenerHandler.

Minimal reproductive scenario:

- add to project `firebase_messaging` and `firebase_core` plugins
- setup firebase plugin
- add handler for background messages

```dart
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();

  log('Handling a background message: ${message.data}');
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  runApp(const MyApp());
}
```

The main problem it's a line - `FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);`

**Comment by alien190** [comment]
Hi @NiKoTron 

Thank you for the issue and the PR. You really helped us to fix this problem. 
The new release 2.2.7 has been published. Could you please try it?

Thank you and have a nice day.

**Comment by NiKoTron** [comment]
I've updated to the latest 2.2.7 now it's works. 🦾
