### ISSUE TITLE
[Android] In-app billing API version 3 is not supported on this device

### ISSUE THREAD

**Issue by mit-73** [apphud/ApphudSDK-Flutter#43]
I get this error after executing `Apphud.start(...)`: `W/BillingClient( 4910): In-app billing API version 3 is not supported on this device.`.

This error is most likely due to the fact that my device does not have an added google play account.

Perhaps we should add a method to check the availability of in-app billing/in-app purchases?

**Comment by ren6** [comment]
Closing due to date
