### ISSUE TITLE
Apphud.hasPremiumAccess() does not work in v2.4.3 and v2.4.4.

### ISSUE THREAD

**Issue by deniell** [apphud/ApphudSDK-Flutter#64]
Apphud.hasPremiumAccess() does not work in v2.4.3 and v2.4.4. I have created new sendbox user for tests on iOS device, reinstalled my app and still have access to all paid functionality. Apphud.hasPremiumAccess() always return true.

**Comment by ren6** [comment]
@deniell hello!
Probably this is because your user had previous purchases. Creating new sandbox user in not enough, you should also delete test user in Apphud to avoid merging with old purchases.
See here: https://docs.apphud.com/docs/testing#test-a-fresh-install-1
